### ISSUE TITLE
Diskusi awal

### ISSUE THREAD

**Issue by dudung** [sutiadiraden/research_idea#1]
Pak @sutiadiraden Ysh., kita dapat mulai diskusi di sini, meliputi ide, algoritma, data yang tersedia, benchmark, piranti lunak / pustaka Python yang digunakan dan lain-lain. 

Bila sudah cukup spesifik, dapat membuat [issue baru](https://github.com/sutiadiraden/research_idea/issues/new) dan diberi judul yang spesifik sehingga mudah dicari.

**Comment by sutiadiraden** [comment]
kemarin itu ada peneliti Mangrove , diskusi dengan saya tentang masalah alat yang bisa membaca arah arus di ekosistem mangrove, fungsi alat itu  membaca dan merekam arah arus ke arah mana saja , dan pola arusnya bagaimana, alat yang saya perlukan modul gps arduino. data loger for arduino . kemdian dibuat semacam frame gimbal  yang fleksibel bisa mengikuti arah  arus air laut. itu device hardwarenya , secara algoritma programnya belum  saya palajari , mungkin jadi berapa dimensi , bergerak ke arah utar selatan, timur barat. pemograman untuk memakai pemograman python mungkin harus ganti dengan resberry pi biar bisa berjalan programnya .

**Comment by sutiadiraden** [comment]
Untuk idenya Pak  kalau pada proposal Deteksi kemudian identifikasi, mengunakan algoritma Yolo, dengan libray python OpenCV untuk pengenalan objeknya, anaconda untuk perangkat lunak. data tersedia berupa foto dan video underwater yang diambil pada saat transek terumbu karang , pada percobaan kemarin jauh dari nilai 90% untuk deteksi nya , dikarenakan baru sedikit dataset yang ditrain pada mechine learningnya , terutama waktu di uji coba di lab karang yang dipengaruhi sinar ultra violet pada aquarium,  ternyata warna sinar ultra violet sangat berpengaruh  pada proses deteksi  nya seperti pada gambar ini  
![uji coba lab terumbu karang1](https://user-images.githubusercontent.com/99871072/198883477-d4c06a2a-6518-45ce-84a4-caa93a096d7f.jpeg)
![uji coba lab terumbu karang2](https://user-images.githubusercontent.com/99871072/198883483-e2808159-8332-4177-ae02-8bc746dc2f6c.jpeg)
sedangkan uji pada citra di darat akurasi deteksi nya sangat bagus 
![WhatsApp Image 2022-08-18 at 11 39 02 AM](https://user-images.githubusercontent.com/99871072/198883711-f9ce9322-3b8c-43bc-bc51-54237e94d34d.jpeg)

**Comment by dudung** [comment]
Angka-angka di atas menggambarkan apa, Pak @sutiadiraden? Lalu apakah semua jenis sudah ada datasetnya? Atau memang tahap awal adala membuat semua dataset dulu? Bila ya, mungkin perlu dengan beberapa sudut pandang dan pecahayaan berbeda sehingga lebih lengkap.

Lalu selain murni dengan ML dapat juga diupayakan mengekstrak ciri-ciri fisis seperti:
- warna,
- ukuran relatif terhadap koloni (bila membententuk koloni),
- variasi keragaman (bila suatu jenis cenderung berkumpul dengan jenis tertentu saja),
- lain-lain (yang Pak @sutiadiraden dan tim sering amati, ini merupakan knowledge yang berharga untuk sistem ML yang akan dibangun).

**Comment by sutiadiraden** [comment]
Angka-angka diatas sebagai indikator berapa persen keakuratan indentifikasi ML nya , untuk semua jenis datasetnya ada Pak @dudung tetapi tidak dalam satu lokasi mungkin mengambil dari beberapa lokasi lain yang ada di Indonesia ada jenis-jenis tertentu yang hidup di lokasi Indonesia bagian timur dan barat , Betul Pak tahap awal membangun dataset pembagian kelas berdasarkan jenis, koloni, pelabelan dan sifat pertumbuhannya. Betul sekali Pak harusnya mengambil gambar sesuai pengamatan beberapa kejadian seperti siklus alam contohnya beberapa sudut pandang pengambilan foto underwater , waktu pencahayaan siang dan malam. kondisi perairan jernih atau keruhnya , visibility pada saat pengambilan gambar , dan kedalaman lokasi transek.
untuk warna dalam beberapa species beragam , begitu juga ukuran koloni , variasi yang berkumpul dengan jenis lain mungkin kedapannya dengan cara segmentasi untuk mencari pendekatan bentuk bentuknya yang tidak beraturan dan untuk  membedakan dengan koloni lain. supaya konsisten  deteksi objek nya ,  ini juga saya baru baca "metode Salient Object Detection" untuk segmentasi Pak belum saya pelajari  Terimakasih Pak @dudung

**Comment by dudung** [comment]
Angka yang baik berarti mendekati 1 ya, Pak?

**Comment by sutiadiraden** [comment]
Iya betul Pak, Semakin banyak sumber dataset nya semakin tinggi angka nya , juga  ada beberapa jenis karang hias yg di jual oleh para eksportir karang hias, yang hidup pada kedalaman 25-40 meter. yang saya harus koleksi  foto-foto nya , untuk datassetnya Pak.

**Comment by dudung** [comment]
Just curios, Pak. Apakah Bapak sebagai pakar dapat selalu membedakan jenis-jenis karangnya dari foto? Bila ya, pengetahuan Pak @sutiadiraden ini yang perlu diajarkan ke mesin (ML), akan tetapi bila masih ada yang meragukan, ini yang perlu kita kaji lebih dalam karena verifikasinya masih membutuhkan cara lain.

**Comment by sutiadiraden** [comment]
saya bukan pakarnya Pak untuk membedakan jenis karang dari sumber foto pasti bisa dan memang sekarang yang dipakai metode nya UPT _under water photo transect_ saya, hanya sering terlibat saja dalam kegiatan monitoring selain menyelam dan mengambil foto bawah air juga kadang menganalisa data nya, jadi hanya beberapa jenis saja yang saya tau ,  sedangn untuk identifikasi jenis ada para peneliti karangnya sendiri, kebetulan di kantor saya termasuk kedalam kelompok riset ekosistem kesehatan terumbu karang, jadi kalau nanti saya mengelompokan  dataset berdasarkan jenis nya pasti beberapa jenis yang belum saya ketahuai dan perlu batuan pakarnya Pak, 
![contoh-upt-1024x768](https://user-images.githubusercontent.com/99871072/198938426-b401b4fe-150c-4c5c-a474-633ced4625cf.jpg)
contoh metode UPT keliatan jenis karang nya hanya ada 2 jenis karang dalam 1 feame transek yaitu seriatofora histrix dan montifora. lalu hasil foto di analisa memakai aplikasi CpCe  (Coral Point Count With Excel Extentions) jadi di sebar beberapa titik di sekitar daerah frame sebanyak 30 titik  secera rendom , dan secara manual juga kita harus memberi nama-nama berdasarkan kode karang nya pada setiap titik tersebut ,  perlu kerja dua kali setelah dapat foto baru di analisa lagi , seperti pada gambar ilustrasi   
![Ilustrasi-CPCE-1024x576](https://user-images.githubusercontent.com/99871072/198939247-b9f1337e-b861-44c4-a1cd-800a0e7c0069.png)

**Comment by dudung** [comment]
![image](https://user-images.githubusercontent.com/7240685/198942537-2499375e-e577-46b6-97db-6f8400a67bd3.png) no 1 di sini berkorespondensi dengan  ![image](https://user-images.githubusercontent.com/7240685/198942598-f6d17fc6-4174-4dd7-bc67-8f9108ebaab5.png) di layar ya, Pak. Berarti untuk contoh di atas belum dituliskan jenis-jenis karangnya pada tabel di samping kanan?

**Comment by sutiadiraden** [comment]
Betul Pak @dudung  titik ke 1 itu jatuhnya di mana tepat pada karangnya atau non karang , apabila titiknya tepat di karangnya di kasih kode karang di kotak no 1 sebelah kanan,  kode karangnya diambil dari bentuk pertembuhan karangnya dan nama species karang , misalkan no 1 itu kode karang CF (Coral Folios) berbentuk lembaran seperti daun. jenisnya diketik pada kolom Notes  Montifora misalkan . seperti itu Pak

**Comment by dudung** [comment]
Jadi semakin banyak titik seharusnya semakin baik ya, Pak? Tapi pekerjaan semakin lama. Dengan demikian perlu cukup banyak titik (tetapi tidak terlalu banyak) akan tetapi kesalahan identifikasi cukup rendah. Suatu permasalahan optimasi yang menarik.

**Comment by sutiadiraden** [comment]
Betul sekali itu sudah Pak ,  kelebihan dan kekuranganya pada metode UPT permasalahanya disitu. diambil 30 titik batas minimal titik acak yang representatif. dulu waktu masih metode LIT dengan cara pengamatan langsung dan mencatatnya pada kertas underwater , butuh waktu penyelaman selama 2 jam,  dengan pengamatan garis transek sepanjang 100 meter  penyelam bahkan bisa ganti tabung samapi 2 kali. jadi antara metode LIT waktu kerja nya lama di bawah air, sedangkan metode UPT wktu kerja di bawah air  sebentar (cukup foto-foto frame sepanjang garis transek sebanyak 50 frame)  proses analisa data di daratnya yang cukup lama.

**Comment by dudung** [comment]
Terima kasih, Pak. Mungkin ini bisa menjadi salah satu problem yang dapat dipecahkan. Setidaknya mencari cara yang lebih optimum, terlebih bila kegiatannya amat kerap dan data yang ingin diolah amat masif. Sudah tidak lagi boleh secara manual.

**Comment by sutiadiraden** [comment]
Betul Pak Dudung ,  sementara lokasi monitoring terumbu karang seluruh indonesia dari bagian barat sampai timur total lokasi statsiun penelitian monitoring seluruhnya ada  24 lokasi, dalam 1 lokasi rata-rata ada 12 titik penelitian, dalam satu titik transek ada 50 frame total 1500 point yang harus di identifikasi, belum lagi di tambah statsiun pembanding seperti bali , lombok , bunaken, wakatobi aru, teluk tomini dan teluk cendrawasih.  metode ini sudah dipakai oleh beberapa universitas UNDIP, IPB, UNRAM, UNHASS, UNSRAT, UGM, UNDANA dan LSM yang terkait dengan kelestarian terumbu karang  di Indonesia 

![image](https://user-images.githubusercontent.com/99871072/199142076-79a1c44a-b652-4bf7-92e4-084fcb362de4.png)
yang saya bayangkan transek dengan sistem AI berbasis Python tinggal menyelam memakai scooter yang ada video cam , tinggal lewat melintasi jalur meteran transek , lalu video hasil nya di upload ke sistem secara otomatis sistem mendetaksi dan keluar angka hasil persentasi tutupan karangnya berapa persen , dan nilai itu untuk menilai ekosistem  terumbu karang dalam katagori baik, sedang, atau buruk . jadi tidak harus melibatkan pakar ketika melakukan monitoring, siapa saja bisa melakukanya. 
begitu kira-kira Pak Dudung selanjutnya,  kemudian mendeployment mesin learning itu menjadi sebuah framework berbasis website agar semua bisa mengunakannya secara online , mimpi nya seperti itu Pak Dudung maaf , kebanyakan mimpi Pak hehehe

**Comment by dudung** [comment]
Alhamdulillah masih memiliki mimpi, Pak. Dewasa ini bahkan untuk bermimpi pun perlu keberanian. Kita coba wujudkan dengan langkah-langkah terstruktrur ya, Pak. Jadi tesis di S2 Sains Komputasi menjadi satu milestone dari impian tersebut. InsyaAllah.

Saya masih belum paham istilah garis transek, Pak @sutiadiraden. Apa artinya dan apa istilah dalam bahasa Inggrisnya? Terima kasih.

**Comment by sutiadiraden** [comment]
aamiin ya rabbal alamin, in sya allah Pak , itulah belajar langsung  dari para pakar nya di ITB biar terstruktur dari algoritma pemogramannya sampai ke formula-formulanya ,. iya Pak Dudung garis transek permanen itu yang di pasang di ekosistem karang sepanjang  100 meter dari patok titik nol sampai titik terakhir 100 m, kemudian dibentangkan meteran roll , sebagai acuan atau garis referensi untuk meletakan frame pada meter 1 dan seterusnya  sampai 100 m . garis transec ditandai dengan  patok besi beton dan dikasih tanda pelampung untuk memudahkan pencarian di monitoring berikutnya .kemduan  posisinya di plot  memakai GPS 
![image](https://user-images.githubusercontent.com/99871072/199172339-9778b1f0-0cac-44fd-9b86-fc27faf5dcf9.png)
contoh gambar garis transek dan pengambilan gambar metode UPT dalam bhs ingrisnya line transect , sedangkan ukuran frame besi untuk acuan pemotretan 44x58 cm.

**Comment by dudung** [comment]
Frame besi yang dimaksud adalah kotak-kotak berwarna merah dengan nomor 1, 2, 3, sampai 50 di atas ya, Pak?

**Comment by sutiadiraden** [comment]
Iya betul Pak , hanya 50 frame yang di ambil fotonya sepanjang 50 m  secara zig zag angka ganjil diatas genap di bawah,  angka ganjil arahnya biasanya mendekati pulau arah ke laut dangkal, sedangkan genap di bawah mengarah ke laut dalam atau tubir, slop, atau wall teragntung counter sea floor nya.  hasil foto yang di analisa hanya dalam lingkup frame tersebut, barapa persen karang jenis A, B, C... dalam frame tersebut jenis karang , dalam kode karang  yang mendominasi dalam satu garis transek contoh perhitungan analisa data 
![image](https://user-images.githubusercontent.com/99871072/199224837-639250c4-ea86-44f1-a9f9-0790e349bbac.png)
foto garis transek 
![PB092157](https://user-images.githubusercontent.com/99871072/199224970-2c7c93c5-1dbd-4374-8033-0447ff56ae42.JPG)
![PB081998](https://user-images.githubusercontent.com/99871072/199224982-225d251d-1cfd-4edd-b6e6-dec582ace7c0.JPG)

**Comment by dudung** [comment]
+ Garis transek itu tertanam permanen di laut dan dianggap tidak berubah selama bertahun-tahun?
+ Kontur (adanya bukit / lembah) dari karang diabaikan dan dianggap mendatar?
+ Apakah ada kasus di mana pada satu frame tadinya karang A sekarang menjadi karang B, padahal yang sebelumnya tertutup di bawahnya? Atau hal ini tidak mungkin?

**Comment by sutiadiraden** [comment]
betul Pak, yang permanen ditanam ialah ,  patok besi beton , di meter 0 dikasih 2 batang besi, di titik 50 meter 1 batang besi beton, kemudian di 100 m 2 batang besi beton, untuk  membedakan titik 0 dan titik akhir yaitu di 100 m,  di ikat pelampung plastik

**Comment by sutiadiraden** [comment]
- Betul Pak, yang permanen ditanam ialah , patok besi beton , di meter 0 dikasih 2 batang besi, di titik 50 meter 1 batang besi beton, kemudian di 100 m 2 batang besi beton, untuk membedakan titik 0 dan titik akhir , diikat pelampung plastik 1 palampung dititik 0, dan ditiik akhir 2 pelampung kemudian di ikatkan tali nylon membentang dari patok 0 sampai patok 100, untuk referensi jalur meteran apabila akan melakukan transek monitoring karang .
- Iya Pak kontur pertembuhan karang diabaikan untuk monitoring karang ,  khusus untuk mengukur kontur pertumbuhan karang dengan metode rugositas 
-   secara normal  pertumbuhan karang sangat lambat, dalam 1 thn untuk karang bercabang tumbuh 1 cm. begitu juga jenis karang lainnya, terkecuali dalam waktu lama (bertahun-tahun) bisa terjadi perubahan dominasi pertumbuhan pada frame misalnya karang A mendominasi pada frame di 5m, kemudian 3 thn kemudian menjadi karang B, tetapi karang A nya masih ada pertumbuhannya lambat atau mati menjadi (Dead Coral With Algae), banyak faktor yang mempengaruhi perubahan dominasi , diantaranya faktor alam gempa bumi seperti yang terjadi di Nias Utara, terjadi pergesaran lempeng bumi yang dulunya karang pada kedalaman 7 m , setelah terjadi gempa terangkat naik menjadi kedalaman 3 m, bahkan ada yang naik kepermukaan.  faktor manusia mencari ikan dengan bom. tatapi untuk jangka waktu 1 thn jarang terjadi perubahan dominasi.

**Comment by dudung** [comment]
Terima kasih atas penjelasannya yang lengkap, Pak @sutiadiraden. Amat mencerahkan.
